Update File with New Glossary Terms
eosnetworkfoundation/docs pull request #28
Opened 2022-10-22 16:34 UTC by VEG-Ginna

New glossary terms added to glossary

Resolves #12

2022-11-08 16:13 UTC, iamveritas requested changes
please replace all EOSIO with Antelope
see my comments below, I did not go through all occurrences for EOSIO.

2022-11-08 17:10 UTC, VEG-Ginna commented on glossary.md
>  For non-standards accounts, those under 12 characters, EOSIO based blockchains provide a system where blockchain users can bid on accounts by submitting the bids via an auction process. Only one acco
Done

2022-11-08 17:10 UTC, VEG-Ginna commented on glossary.md
>  Functionality exposed by a smart contract that is exercised by passing the correct parameters via an approved transaction to an EOSIO network.
Done

2022-11-08 17:10 UTC, VEG-Ginna commented on glossary.md
>  30% of EOSIO development funded by Telos, WAX, and UX
Done

2022-11-09 17:07 UTC, iamveritas approved these changes

2022-11-09 17:13 UTC, merged